[package]
name = "automata-z3-graphviz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peg = "0.8"
petgraph = "0.6.0"
opener = "0.5.0"
clap = { version = "3.0.7", features = ["derive"] }
